# Prometheus configuration file
# Configurations assume both the When In Rome project and Prometheus are running locally.

global:
  scrape_interval: 10s # Set the default scrape interval to every 10 seconds.
  evaluation_interval: 10s # Evaluate rules every 10 seconds.

# Configuration configs specific to this project
scrape_configs:
  - job_name: 'When in Rome Scrape'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8080']